### ISSUE TITLE
errror in LAMMPS example

### ISSUE THREAD

**Issue by alvarovm** [libAtoms/pymatnest#2]
Hi, I cannot run the lammps test examples, it seems like a variable is missing. 
I get the follow error:

$>mpirun -n  2 ../ns_run < inputs.test.cluster.MC.lammps 
WARNING: no quippy module loaded
WARNING: no quippy module loaded
comm  <mpi4py.MPI.Intracomm object at 0x7f66f1d06900>  size  2  rank  0
comm  <mpi4py.MPI.Intracomm object at 0x7f00f2fcf900>  size  2  rank  1
Traceback (most recent call last):
  File "../ns_run", line 6, in <module>
Traceback (most recent call last):
  File "../ns_run", line 6, in <module>
    ns_run.main()
  File "/home/vama/soft/pymatnest/ns_run.py", line 2606, in main
    ns_run.main()
  File "/home/vama/soft/pymatnest/ns_run.py", line 2606, in main
    exit_error("need either n_iter_times_fraction_killed or converge_down_to_T")
TypeError: exit_error() takes exactly 2 arguments (1 given)
    exit_error("need either n_iter_times_fraction_killed or converge_down_to_T")
TypeError: exit_error() takes exactly 2 arguments (1 given)

**Comment by noambernstein** [comment]
Example script must have fallen out of date with some syntax change. If no one else does before then, I'll take a look tomorrow.

     Noam

**Comment by gabor1** [comment]
We put in the argument it asked about, then it complained about lammps atom types. 

-- Gábor

**Comment by noambernstein** [comment]
> On Nov 16, 2016, at 8:10 PM, gabor1 <notifications@github.com> wrote:
> 
> We put in the argument it asked about, then it complained about lammps atom types. 

At some point we started requiring a conversion from ASE species to Lammps atom types. I'll update the example input and let you know when it's ready. Bad form to have let it get out of date, but that's what happens when you don't do automated testing.

   Noam

**Comment by noambernstein** [comment]
The version of the example input file already has the
n_iter_times_fraction_killed argument  as well as a LAMMPS_atom_types.
The only supported files are the ones in example_inputs/.  Is that
where you're looking?  And is it the latest gitlab version?

I'd be happy to move the other old example directories to some
directory, or get rid of them altogether.

    Noam

**Comment by gabor1** [comment]
He was just following the README, and using the scripts from the tests_lammps directory

"Example input files for clusters and periodic systems, both with MC and MD, are in the tests/"

I think it would help a lot if you just removed the deprecated input files altogether, and updated the README. they'll be preserved in the git history for posterity.  

thanks for looking into it.  


— Gábor

**Comment by liviabp** [comment]
Sorry, some old info was left in the README, the correct location of the examples were given at the end, under the “documentation” section. I corrected and pushed a new readme file.

Livia

**Comment by noambernstein** [comment]
Does anyone object to removing all the old tests*/ directories and leaving only example_inputs/ ?

      Noam

**Comment by gabor1** [comment]
Can we close this?
